### ISSUE TITLE
Adapt the project for newcomers

### ISSUE THREAD

**Issue by vladfaust** [onyxframework/http#37]
Crystal is growing. I spend so much effort on Prism to make web-development a joy, but seems like I'm the one who's using Prism in production. Let's change it!

- [ ] Remind that the GitHub README is for the master branch
- [ ] Tell that features appear along my needs and I'm open for issues and PRs
- [ ] Prism needs a website
  - [ ] Fancy landing page
  - [ ] Docs either on GitBook or VuePress
- [ ] Adapt for developers new to Crystal
  - [ ] Benchmarks with other languages
  - [ ] Common frameworks code comparison
  - [ ] Note about "catch bugs in development, not in production"
  - [ ] Tell about websockets built-in
- [ ] Adapt for Crystal developers looking for a better web framework
  - [ ] Tell about Prism modularity when you decide what to include
  - [ ] Tell about Prism object-oriented approach when where are no global configuration objects which allows to have multiple servers and routers in one application
  - [ ] Tell about versatile callbacks system
  - [ ] Tell about strict params typecasting which reduces amount of code and improves security drastically
  - [ ] Tell about versatile authentication module
- [ ] Add project template

**Comment by jackturnbull** [comment]
I'm only just starting to use it so I'll try and chip in with as much feedback as possible. I ended up here instead of lucky because I liked how modular and composable it felt - instead of getting everything I could possibly need and then stripping it back down again. Could be useful to focus on that I suppose?

It'd be a larger piece of work and one that I can appreciate you may not have time for but a simple project template would likely be quite useful. Like crystal world, but no content.

**Comment by vladfaust** [comment]
Closed due to the project takeover by @onyxframework
